# Model Description

Below I assume the generative model to be a Generalised Linear Model (GLM) with the response variable (total corners) following a poisson distribution. 

I.e. we assume that a linear combination of input feature vectors is equal to the logarithm of the expected value of the poisson distribution: 

$$total corners = Y$$

$$features = X$$

$$log(E(P(Y|X;\lambda)) = \beta X$$

Where $\beta$ is a vector of coefficients

# Implementation

For our input features we take the variables: leagueId,HomeTeamId and AwayTeamId. We ignore goals because they are not known prior to the match. We also ignore matchID as it is a unique ID and thus has no correlation with our response variables distribution. Future improvements could use the match day as an additional categorical variable in the input feature vector. 

As we are dealing with categorical variables we must first one-hot encode them so that our model is interpretable. We do this also to prevent any implicit order bias in the feature vectors. Unfortunately since the team categorical variable has 333 levels we may later deal with issues related to overparameterisation when optimising. I discuss this further below. 

We optimise the model by finding the maximum likelihood estimate for the parameters. As the MLE does not have a analytical form we instead use numerical optimisation through the Statsmodel python library. Further explained below.

In [2]:
#Import statements
%matplotlib inline
import numpy as np
import pandas as pd
import pymc3 as pm
from scipy import stats
import matplotlib.pyplot as plt
from statsmodels.api import Poisson,NegativeBinomial
pd.options.display.max_rows = 20

WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\ProgramData\Anaconda3\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

In [9]:
#Import raw data
train_raw = pd.read_csv("./Datasets/Football Corners/train.csv")
test_raw = pd.read_csv("./Datasets/Football Corners/test.csv")
train_drop_list = ['Home_Goals','Away_Goals','Date','MatchId','Home_Corners','Away_Corners']
test_drop_list = ['Date','MatchId','Unnamed: 8','P(Under)','P(Over)','Bet (U/O)','Stake','Line','Over','Under','P(At)']

In [53]:
# Find set union of all teams among both test and train set. Same for leagues
teams = set(train_raw['HomeTeamId']).union(set(train_raw['AwayTeamId']),
                                           set(test_raw['HomeTeamId']),set(test_raw['AwayTeamId']))
leagues = set(train_raw['LeagueId']).union(set(test_raw['LeagueId']))
teams = sorted(teams)
leagues = sorted(leagues)

In [58]:
# Create copies of df for dummy/one-hot encodings
train_dummy = train_raw.copy()
test_dummy = test_raw.copy()

# Replace home/away corners with total corners for game
train_dummy['Total_Corners'] = train_dummy['Home_Corners'] + train_dummy['Away_Corners']
train_dummy = train_dummy.drop(train_drop_list,axis=1)
test_dummy = test_dummy.drop(test_drop_list,axis=1)

# Add total set of teams and leagues to categorical columns
train_dummy['HomeTeamId'] = train_dummy['HomeTeamId'].astype('category',categories=teams)
train_dummy['AwayTeamId'] = train_dummy['AwayTeamId'].astype('category',categories=teams)
train_dummy['LeagueId'] = train_dummy['LeagueId'].astype('category',categories=leagues)
test_dummy['HomeTeamId'] = test_dummy['HomeTeamId'].astype('category',categories=teams)
test_dummy['AwayTeamId'] = test_dummy['AwayTeamId'].astype('category',categories=teams)
test_dummy['LeagueId'] = test_dummy['LeagueId'].astype('category',categories=leagues)

# Create one hot dummy encodings for cat variables
train_dummy = pd.get_dummies(train_dummy,columns=['HomeTeamId','AwayTeamId','LeagueId'],
                             prefix=['HomeTeam','AwayTeam','League'],drop_first=True)
test_dummy = pd.get_dummies(test_dummy,columns=['HomeTeamId','AwayTeamId','LeagueId'],
                            prefix=['HomeTeam','AwayTeam','League'],drop_first=True)

In [55]:
# Cleaned train data format
train_dummy

,Total_Corners,HomeTeam_196,HomeTeam_197,HomeTeam_214,HomeTeam_216,HomeTeam_224,HomeTeam_232,HomeTeam_238,HomeTeam_243,HomeTeam_246,...,League_764,League_776,League_781,League_793,League_795,League_800,League_801,League_811,League_813,League_816
0,16,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,15,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,7,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
5,15,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
6,13,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,10,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,7,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,16,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23820,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23821,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23822,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23823,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23824,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23825,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23826,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23827,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23828,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23829,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

# Model Optimisation

Below we find the Maximum Likelihood Estimation of our parameters. Initially attempts at optimising this using Newton's method failed to converge. I believe this is due to an overparameterisation issue caused by the size of our input feature vector (665). It may also be due to collinearity caused by the one-hot encoding of categorical variables. Using the quasi newton BFGS method succeeded, albeit after 195 iterations. 

This is one reason why I had to opt out of using a Negative Binomial Distribution for total corners. Which has greater flexibility than the poisson distribution due to not having the limitation of mean = variance. However, due to the difficulty optimising the model I decided not to use it.

In [8]:
# Seperate train dataset to input feature vector and output variable
x = train_dummy.iloc[:,1:]
y = train_dummy.iloc[:,0]

p_mod = Poisson(y,x)
mod_results = p_mod.fit(method='bfgs',maxiter=200)

Optimization terminated successfully.
         Current function value: 2.602546
         Iterations: 192
         Function evaluations: 195
         Gradient evaluations: 195

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\model.py:492: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)

In [56]:
# Predicted total corners vs actual for train set
train_pred = mod_results.predict(x)
print("Train mean: {}, Train variance: {}".format(y.mean(),y.var()))
print("Prediction mean: {}, Prediction variance: {}"
      .format(train_pred.mean(),train_pred.var()))
print(pd.concat([train_pred,y],axis=1))

Train mean: 10.21947125472094, Train variance: 11.915991663007658
Prediction mean: 10.219474147681458, Prediction variance: 0.969447416774784
               0  Total_Corners
0      11.748342             16
1      10.575970              9
2      10.868216             15
3      10.569455              7
4      11.208936              9
5      11.715234             15
6      10.982199             13
7      10.715858             10
8       9.877708              7
9      11.283169             16
...          ...            ...
23820   9.696382             11
23821   7.804945              8
23822   8.157372              6
23823  10.514358             11
23824  10.059380              8
23825  10.517805              9
23826  11.179371              7
23827  10.105730              8
23828  11.401140             10
23829   9.760997             10

[23830 rows x 2 columns]

# Observations and Improvements

Above we can qualitatively observe that while our model predicts an average value close to the average number of total corners (~10), it has significantly less variance as compared to the truth values. 

#### Train mean: 10.21947125472094, Train variance: 11.915991663007658

#### Prediction mean: 10.219474147681458, Prediction variance: 0.969447416774784

Below we use the model's MLE parameter estimates to find the required probabilities. We do this using the CDFs and PMFs of the poisson distribution with our predicted rates. (test_pred)

# Calculating probabilities and choosing bets

Below we apply our model to the test set. We then calculate the predicted probabilities of being over, under and at the line. 

We choose to bet on the outcome that has the highest probability. 

### The stake amount is dependent on the amount of risk you are willing to take, i.e. the percentage of your bettable capital you are willing to lose. 
### It is also dependent on the reliability of your model's outputs. If you wanted to shape the risk profile of your position you would hold opposing positions (hedge) to get the expected return and risk you desired.

In [21]:
# Get predicted rates for test dataset
test_pred = mod_results.predict(test_dummy)
test_output = test_raw.copy()

# Calculate probabilities and add them to dataframe
p_under = stats.poisson.cdf(np.ceil(test_output['Line']-1),test_pred)
p_at = stats.poisson.pmf(test_output['Line'],test_pred)
p_over = 1 - (p_under + p_at)

test_output['P(Under)'] = p_under
test_output['P(At)'] = p_at
test_output['P(Over)'] = p_over

In [22]:
# Decide to bet over or under
def calculateBetStake(row):
    if (row['P(Under)'] > row['P(Over)']):
        return 'Under'
    elif (row['P(Over)'] > row['P(Under)']):
        return 'Over'
    else:
        return 'Neither'

test_output['Bet (U/O)'] = test_output.apply(lambda row: calculateBetStake(row),axis=1)

In [59]:
test_output.to_csv("test_output.csv")
test_output

,MatchId,LeagueId,Date,HomeTeamId,AwayTeamId,Line,Over,Under,Unnamed: 8,P(Under),P(At),P(Over),Bet (U/O),Stake
0,1,741,01/04/2011,342,694,9.5,1.790,1.800,NaN,0.599605,0.000000,0.400395,Under,NaN
1,2,741,01/04/2011,1424,270,11.5,1.920,2.000,NaN,0.564578,0.000000,0.435422,Under,NaN
2,3,729,01/04/2011,691,1137,10.5,1.970,1.870,NaN,0.499559,0.000000,0.500441,Over,NaN
3,4,729,01/04/2011,787,808,11.0,2.075,1.770,NaN,0.582482,0.113787,0.303731,Under,NaN
4,5,741,01/04/2011,784,1117,12.0,2.020,1.860,NaN,0.566734,0.110419,0.322846,Under,NaN
5,6,776,01/04/2011,914,1089,9.5,1.970,1.850,NaN,0.645346,0.000000,0.354654,Under,NaN
6,7,776,01/04/2011,1423,1180,10.0,1.970,1.850,NaN,0.406512,0.124037,0.469451,Over,NaN
7,8,801,01/04/2011,258,489,9.0,1.870,1.800,NaN,0.403252,0.130579,0.466169,Over,NaN
8,9,801,01/04/2011,1253,1223,10.0,1.920,1.920,NaN,0.549109,0.121853,0.329038,Under,NaN
9,10,795,01/04/2011,627,831,9.0,2.020,1.890,NaN,0.288162,0.119136,0.592702,Over,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,332,729,22/05/2011,1193,445,11.0,1.940,1.971,NaN,0.602499,0.111830,0.285672,Under,NaN
332,333,795,22/05/2011,1278,320,9.5,1.960,1.917,NaN,0.476154,0.000000,0.523846,Over,NaN
333,334,793,22/05/2011,486,956,10.5,1.922,1.850,NaN,0.581726,0.000000,0.418274,Under,NaN
334,335,811,22/05/2011,991,316,10.0,2.010,1.791,NaN,0.501082,0.124374,0.374544,Under,NaN
335,336,729,22/05/2011,1137,338,10.0,1.861,2.020,NaN,0.478295,0.124945,0.396760,Under,NaN
336,337,729,22/05/2011,1211,1118,10.5,1.950,1.961,NaN,0.535223,0.000000,0.464777,Under,NaN
337,338,795,22/05/2011,1116,876,10.0,1.920,1.909,NaN,0.415620,0.124386,0.459994,Over,NaN
338,339,801,22/05/2011,1223,771,10.0,2.020,1.840,NaN,0.529164,0.123115,0.347721,Under,NaN
339,340,801,22/05/2011,238,570,10.5,2.020,1.900,NaN,0.482979,0.000000,0.517021,Over,NaN
340,341,776,23/05/2011,412,1089,10.5,2.220,1.729,NaN,0.671006,0.000000,0.328994,Under,NaN